### ISSUE TITLE
what are the fundamentals here?

### ISSUE THREAD

**Issue by carl-binding** [IBM/detect-timeseriesdata-change#10]
A lot of machinery to run some rudimentary statistics on small data-sets. Oh boy.
How well grounded is the approach of detecting changes in a time-series? no references are given, the proposed methodology appears to be of ad-hoc nature and not grounded in science.

**Comment by dkprabu** [comment]
@carl-binding 
The idea is to show how to tie together, the data collection from an IoT sensor and then store the data in a database followed by a simple first level analysis in IBM DSX on the cloud and show the Analytics results. Please see the video that gives a walk through.

Some underlying thoughts behind this code set
1. The parameters are completely modularised so that the whole thing can be rerun on different datasets by simply changing the  configuration parameters (lending itself to automation with some code extensions)
2. The design is flexible to handle data collection and processing from any number of sensors (see the generic design of database table to store any sensor data)
3. The approach helps automation of detecting change points less manual intervention (visualisation requires eyeballing manually), but converting them into a single statistical number helps in automated scrutiny (may be first level)
4. The focus of this flow is not to prove a new or unique statistical technique or algorithm but to show a sample of the possibility. There may be other advanced techniques that are IP protected which is not part of this flow as that is not the intention here. Modularising and open sourcing the code means you can pick the code and embed your own algo and deploy easily. See the function that handles the algo in the repo, you can isolate and change this specific function to suit your requirement.
5. This also doesn't cover areas that are already covered by pre-existing IBM Developer journeys. Please check the full repository of IBM developer journeys here. https://developer.ibm.com/code/patterns/?cm_sp=Developer-_-Top-Nav-_-Journeys
6. And this is the first in a series of IBM Code patterns planned out in this space, and few others are in works. The idea is, if you pick out the ones that most suit your needs you can put together a end to end solution with no or minimal effort. You can further customize as the code is all open sourced. Do look out for the IBM pattern link above.
7. Finally, scalability is addressed by the whole flow running on IBM cloud with Data Science experience running on Spark
 
Hope that helps clarify

**Comment by dkprabu** [comment]
Hint 1: You can use the list of 16+ base stats that the function generates in different combinations to calculate derived metrics that mimic what we humans visually look for when we compare 2 boxplots. This will again depend on your specific application / equipment / Sensor / measurements units etc., Lots of creative scope for developer with Code extensions here.
Hint 2: Use the above function to generate a series of box plots, to visualize some exciting patterns in data. You will be surprised with the results and insights. This will also require code extensions which is not the focus area of this pattern.
